#!/bin/bash
# Asset Renaming Script
# Auto-generated by analyze_assets.py

cd /Users/bipashahalder/Documents/Philanthroforge_Complete_Clone/assets

echo '====================================================='
echo 'Renaming Assets'
echo '====================================================='

# Folder/Philanthro logo.png -> branding/logo.png
cp "Folder/Philanthro logo.png" "branding/logo.png"

# about_build_implement_philanthroforge_how_to_get_more_donation.jpg -> about/process-implement.jpg
cp "about_build_implement_philanthroforge_how_to_get_more_donation.jpg" "about/process-implement.jpg"

# about_content_img.jpg -> about/hero-background.jpg
cp "about_content_img.jpg" "about/hero-background.jpg"

# about_linkedin_philanthroforge_md_shane_ali_fundraising.jpg -> about/team-founder.jpg
cp "about_linkedin_philanthroforge_md_shane_ali_fundraising.jpg" "about/team-founder.jpg"

# about_over_the_last_4_years_we_haveworked_with_philanthroforge_worked_with_platforms_an.jpg -> about/platforms-logos.jpg
cp "about_over_the_last_4_years_we_haveworked_with_philanthroforge_worked_with_platforms_an.jpg" "about/platforms-logos.jpg"

# case-integrated-ecosystems_content_img.jpg -> case-studies/integrated-ecosystems/hero.jpg
cp "case-integrated-ecosystems_content_img.jpg" "case-studies/integrated-ecosystems/hero.jpg"

# case-rewarding-generosity_content_img.jpg -> case-studies/rewarding-generosity/hero.jpg
cp "case-rewarding-generosity_content_img.jpg" "case-studies/rewarding-generosity/hero.jpg"

# case-turning-supporters_content_img.jpg -> case-studies/turning-supporters/hero.jpg
cp "case-turning-supporters_content_img.jpg" "case-studies/turning-supporters/hero.jpg"

# contact_content_img.jpg -> pages/lets-talk-hero.jpg
cp "contact_content_img.jpg" "pages/lets-talk-hero.jpg"

# index_content_img.jpg -> home/hero-background.jpg
cp "index_content_img.jpg" "home/hero-background.jpg"

# index_csr_major_donor_support_philanthroforge_nonprofit_fundraising_ad.jpg -> home/service-csr.jpg
cp "index_csr_major_donor_support_philanthroforge_nonprofit_fundraising_ad.jpg" "home/service-csr.jpg"

# index_digital_fundraising_strategywe_audit_you_philanthroforge_nonprofit_digital_fundra.jpg -> home/service-digital-strategy.jpg
cp "index_digital_fundraising_strategywe_audit_you_philanthroforge_nonprofit_digital_fundra.jpg" "home/service-digital-strategy.jpg"

# index_fundraising_campaign_journey_design_philanthroforge_professional_nonprofit_f.jpg -> home/service-campaign.jpg
cp "index_fundraising_campaign_journey_design_philanthroforge_professional_nonprofit_f.jpg" "home/service-campaign.jpg"

# index_fundraising_consultancy_advisory_philanthroforge_fundraising_advisory_exp.jpg -> home/service-consultancy.jpg
cp "index_fundraising_consultancy_advisory_philanthroforge_fundraising_advisory_exp.jpg" "home/service-consultancy.jpg"

# index_rewarding_generosity_unlocks_new_givingg_philanthroforge_nonprofit_fundraising_co.jpg -> home/case-rewarding-generosity.jpg
cp "index_rewarding_generosity_unlocks_new_givingg_philanthroforge_nonprofit_fundraising_co.jpg" "home/case-rewarding-generosity.jpg"

# index_website_donation_ux_optimization_philanthroforge_fundraising_advisory_exp.jpg -> home/service-website-ux.jpg
cp "index_website_donation_ux_optimization_philanthroforge_fundraising_advisory_exp.jpg" "home/service-website-ux.jpg"

# privacy_content_img.jpg -> pages/privacy-hero.jpg
cp "privacy_content_img.jpg" "pages/privacy-hero.jpg"

# service-brand-identity_brand_strategy_and_positioningwebsite_st_img.jpg -> services/brand-identity/brand-strategy.jpg
cp "service-brand-identity_brand_strategy_and_positioningwebsite_st_img.jpg" "services/brand-identity/brand-strategy.jpg"

# service-brand-identity_content_img.jpg -> services/brand-identity/hero.jpg
cp "service-brand-identity_content_img.jpg" "services/brand-identity/hero.jpg"

# service-brand-identity_visual_identity_system_img.jpg -> services/brand-identity/visual-system.jpg
cp "service-brand-identity_visual_identity_system_img.jpg" "services/brand-identity/visual-system.jpg"

# service-campaign-design_campaign_strategyclear_positioning_of_ca_img.jpg -> services/campaign-design/strategy.jpg
cp "service-campaign-design_campaign_strategyclear_positioning_of_ca_img.jpg" "services/campaign-design/strategy.jpg"

# service-campaign-design_content_img.jpg -> services/campaign-design/hero.jpg
cp "service-campaign-design_content_img.jpg" "services/campaign-design/hero.jpg"

# service-campaign-design_creative_content_img.jpg -> services/campaign-design/creative-content.jpg
cp "service-campaign-design_creative_content_img.jpg" "services/campaign-design/creative-content.jpg"

# service-consultancy_content_img.jpg -> services/consultancy/hero.jpg
cp "service-consultancy_content_img.jpg" "services/consultancy/hero.jpg"

# service-consultancy_decision_making_support_img.jpg -> services/consultancy/decision-support.jpg
cp "service-consultancy_decision_making_support_img.jpg" "services/consultancy/decision-support.jpg"

# service-consultancy_strategic_review_sessionsregular_engagem_img.jpg -> services/consultancy/review-sessions.jpg
cp "service-consultancy_strategic_review_sessionsregular_engagem_img.jpg" "services/consultancy/review-sessions.jpg"

# service-csr-support_content_img.jpg -> services/csr-support/hero.jpg
cp "service-csr-support_content_img.jpg" "services/csr-support/hero.jpg"

# service-csr-support_csr_partnership_materialsstrategic_posit_img.jpg -> services/csr-support/partnership-materials.jpg
cp "service-csr-support_csr_partnership_materialsstrategic_posit_img.jpg" "services/csr-support/partnership-materials.jpg"

# service-csr-support_major_donor_and_grant_narratives_img.jpg -> services/csr-support/donor-narratives.jpg
cp "service-csr-support_major_donor_and_grant_narratives_img.jpg" "services/csr-support/donor-narratives.jpg"

# service-digital-strategy_comprehensive_auditwebsite_structure_and_img.jpg -> services/digital-strategy/audit-section.jpg
cp "service-digital-strategy_comprehensive_auditwebsite_structure_and_img.jpg" "services/digital-strategy/audit-section.jpg"

# service-digital-strategy_content_img.jpg -> services/digital-strategy/hero.jpg
cp "service-digital-strategy_content_img.jpg" "services/digital-strategy/hero.jpg"

# service-digital-strategy_strategic_analysis_improvements_img.jpg -> services/digital-strategy/analysis.jpg
cp "service-digital-strategy_strategic_analysis_improvements_img.jpg" "services/digital-strategy/analysis.jpg"

# service-donation-form_content_img.jpg -> services/donation-form/hero.jpg
cp "service-donation-form_content_img.jpg" "services/donation-form/hero.jpg"

# service-donation-form_form_audit_and_analysiscomprehensive_rev_img.jpg -> services/donation-form/audit-analysis.jpg
cp "service-donation-form_form_audit_and_analysiscomprehensive_rev_img.jpg" "services/donation-form/audit-analysis.jpg"

# service-donation-form_form_redesign_img.jpg -> services/donation-form/form-redesign.jpg
cp "service-donation-form_form_redesign_img.jpg" "services/donation-form/form-redesign.jpg"

# service-donor-analysis_content_img.jpg -> services/donor-analysis/hero.jpg
cp "service-donor-analysis_content_img.jpg" "services/donor-analysis/hero.jpg"

# service-donor-analysis_revenue_performance_assessment_img.jpg -> services/donor-analysis/revenue-assessment.jpg
cp "service-donor-analysis_revenue_performance_assessment_img.jpg" "services/donor-analysis/revenue-assessment.jpg"

# service-donor-analysis_supporter_behaviour_analysisacquisition__img.jpg -> services/donor-analysis/behaviour-analysis.jpg
cp "service-donor-analysis_supporter_behaviour_analysisacquisition__img.jpg" "services/donor-analysis/behaviour-analysis.jpg"

# service-website-optimization_content_img.jpg -> services/website-optimization/hero.jpg
cp "service-website-optimization_content_img.jpg" "services/website-optimization/hero.jpg"

# service-website-optimization_donation_experience_designstreamlined_wo_img.jpg -> services/website-optimization/donation-design.jpg
cp "service-website-optimization_donation_experience_designstreamlined_wo_img.jpg" "services/website-optimization/donation-design.jpg"

# service-website-optimization_key_page_optimization_img.jpg -> services/website-optimization/page-optimization.jpg
cp "service-website-optimization_key_page_optimization_img.jpg" "services/website-optimization/page-optimization.jpg"

# services_content_img.jpg -> services/hero-background.jpg
cp "services_content_img.jpg" "services/hero-background.jpg"

# services_design_systems_not_just_campaigns_philanthroforge_nonprofit_fundraising_ex.jpg -> services/systems-design.jpg
cp "services_design_systems_not_just_campaigns_philanthroforge_nonprofit_fundraising_ex.jpg" "services/systems-design.jpg"

# services_listen_deeply_to_donors_and_data_img.jpg -> services/donor-analysis-graphic.jpg
cp "services_listen_deeply_to_donors_and_data_img.jpg" "services/donor-analysis-graphic.jpg"

# terms_content_img.jpg -> pages/terms-hero.jpg
cp "terms_content_img.jpg" "pages/terms-hero.jpg"

echo ''
echo '====================================================='
echo '✅ Asset reorganization complete!'
echo '====================================================='